token: ''

intents: 6087 # https://ziad87.net/intents/

max_reconnects: 0

manhole_enable: true
manhole_bind: 0.0.0.0:7171

DSN: ''

web:
    CLIENT_SECRET: ''
    SECRET_KEY: ''
    TWITCH_CLIENT_ID: '' # Unfinished, not required... yet.
    DISCORD_CLIENT_ID: ''
    DISCORD_CLIENT_SECRET: ''
    DISCORD_API_BASE_URL: 'https://discord.com/api' #Leave this
    DISCORD_TOKEN_URL: 'https://discord.com/api/oauth2/token' #Leave this
    DISCORD_AUTH_URL: 'https://discord.com/oauth2/authorize' #Leave this
    DISCORD_REDIRECT_URI: ''

state:
  sync_guild_members: true

ENV: 'docker' # Set to 'prod' when prod

bot:
  commands_enabled: false
  plugins:
    - rowboat.plugins.core
    - rowboat.plugins.modlog
    - rowboat.plugins.admin
    - rowboat.plugins.spam
    - rowboat.plugins.censor
    - rowboat.plugins.reddit
    - rowboat.plugins.starboard
    - rowboat.plugins.utilities
    - rowboat.plugins.sql
    - rowboat.plugins.internal
    #- rowboat.plugins.stats
    - rowboat.plugins.level
    - rowboat.plugins.tags
